version: '3'
services:
  vote-tally-redis:
    image: redis
    container_name: vote-tally-redis
    ports:
        - "6379:6379"
  vote-tally:
    build: .
    ports: 
        - "80:5000"
    container_name: vote-tally
    environment:
      REDIS: vote-tally-redis
    